sources:
  - name: raw
    description: Raw data from CSV files
    database: postgres
    schema: raw

    tables:
      - name: census_g01
      - name: census_g02
      - name: listings
      - name: nsw_lga_code
      - name: nsw_lga_suburb
      - name: snapshot_host
      - name: snapshot_listings
      - name: snapshot_property
      - name: snapshot_room
      - name: listings_stg